### PR TITLE
[teleop] Update carousel display

### PR DESCRIPTION
**Pull request by CameronTressler**
Displays "Last at position __" when in open loop.
Displays "Turning to __" when in closed loop and not at the state commanded.
Displays "At position __" when in closed loop and at the state commanded.

image

### CODE REVIEW

**Comment by CameronTressler** [comment]
For some reason can't add Catherine as a reviewer, will send to her as well

**Comment by tabiosg** [comment]
> For some reason can't add Catherine as a reviewer, will send to her as well

Oops I haven't added her to the repo yet, just did though. Once she accepts she can review PRs

**Review by tabiosg — APPROVED** [review]

**Review by catkims — COMMENTED** [review]
When does closed loop get set to true aside from the initial declaration?

**Comment by tabiosg** [comment]
> When does closed loop get set to true aside from the initial declaration?

line 83

**Review by catkims — APPROVED** [review]

**Pull request merged**
